language: android

jdk: oraclejdk8

andriod:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.1
  - android-23
  - extra-android-m2repository

before_install:
  - chmod +x gradlew

script: ./gradlew build