language : android

jdk :
  - oraclejdk8

andriod:
  components:
  - platform-tools
  - tools
  - build-tools-25.0.2
  - android-25
  - extra-android-m2repository

before_install:
  - chmod +x gradlew

script: ./gradlew build